export interface City {
  name: string
  country: string
  region?: string
}

export const cities: City[] = [
  // Germany (50+)
  ...[ {n:'Berlin',r:'Berlin'},{n:'Munich',r:'Bayern'},{n:'Hamburg',r:'Hamburg'},{n:'Frankfurt',r:'Hessen'},{n:'Cologne',r:'Nordrhein-Westfalen'},{n:'Stuttgart',r:'Baden-Württemberg'},{n:'Düsseldorf',r:'Nordrhein-Westfalen'},{n:'Leipzig',r:'Sachsen'},{n:'Dortmund',r:'Nordrhein-Westfalen'},{n:'Essen',r:'Nordrhein-Westfalen'},{n:'Bremen',r:'Bremen'},{n:'Dresden',r:'Sachsen'},{n:'Hanover',r:'Niedersachsen'},{n:'Nuremberg',r:'Bayern'},{n:'Duisburg',r:'Nordrhein-Westfalen'},{n:'Bochum',r:'Nordrhein-Westfalen'},{n:'Wuppertal',r:'Nordrhein-Westfalen'},{n:'Bielefeld',r:'Nordrhein-Westfalen'},{n:'Bonn',r:'Nordrhein-Westfalen'},{n:'Münster',r:'Nordrhein-Westfalen'},{n:'Karlsruhe',r:'Baden-Württemberg'},{n:'Mannheim',r:'Baden-Württemberg'},{n:'Augsburg',r:'Bayern'},{n:'Wiesbaden',r:'Hessen'},{n:'Gelsenkirchen',r:'Nordrhein-Westfalen'},{n:'Mönchengladbach',r:'Nordrhein-Westfalen'},{n:'Braunschweig',r:'Niedersachsen'},{n:'Chemnitz',r:'Sachsen'},{n:'Kiel',r:'Schleswig-Holstein'},{n:'Aachen',r:'Nordrhein-Westfalen'},{n:'Halle',r:'Sachsen-Anhalt'},{n:'Magdeburg',r:'Sachsen-Anhalt'},{n:'Freiburg',r:'Baden-Württemberg'},{n:'Krefeld',r:'Nordrhein-Westfalen'},{n:'Lübeck',r:'Schleswig-Holstein'},{n:'Oberhausen',r:'Nordrhein-Westfalen'},{n:'Erfurt',r:'Thüringen'},{n:'Mainz',r:'Rheinland-Pfalz'},{n:'Rostock',r:'Mecklenburg-Vorpommern'},{n:'Kassel',r:'Hessen'},{n:'Hagen',r:'Nordrhein-Westfalen'},{n:'Hamm',r:'Nordrhein-Westfalen'},{n:'Saarbrücken',r:'Saarland'},{n:'Mülheim',r:'Nordrhein-Westfalen'},{n:'Herne',r:'Nordrhein-Westfalen'},{n:'Ludwigshafen',r:'Rheinland-Pfalz'},{n:'Osnabrück',r:'Niedersachsen'},{n:'Oldenburg',r:'Niedersachsen'},{n:'Leverkusen',r:'Nordrhein-Westfalen'},{n:'Solingen',r:'Nordrhein-Westfalen'},{n:'Potsdam',r:'Brandenburg'},{n:'Heidelberg',r:'Baden-Württemberg'},{n:'Paderborn',r:'Nordrhein-Westfalen'},{n:'Darmstadt',r:'Hessen'},{n:'Regensburg',r:'Bayern'},{n:'Würzburg',r:'Bayern'},{n:'Ingolstadt',r:'Bayern'},{n:'Heilbronn',r:'Baden-Württemberg'},{n:'Ulm',r:'Baden-Württemberg'},{n:'Frankfurt (Oder)',r:'Brandenburg'} ].map(c => ({ name: c.n, country: 'Germany', region: c.r })),

  // United States (50+)
  ...[ {n:'New York',r:'New York'},{n:'Los Angeles',r:'California'},{n:'Chicago',r:'Illinois'},{n:'Houston',r:'Texas'},{n:'Phoenix',r:'Arizona'},{n:'Philadelphia',r:'Pennsylvania'},{n:'San Antonio',r:'Texas'},{n:'San Diego',r:'California'},{n:'Dallas',r:'Texas'},{n:'San Jose',r:'California'},{n:'Austin',r:'Texas'},{n:'Jacksonville',r:'Florida'},{n:'Fort Worth',r:'Texas'},{n:'Columbus',r:'Ohio'},{n:'Charlotte',r:'North Carolina'},{n:'Indianapolis',r:'Indiana'},{n:'San Francisco',r:'California'},{n:'Seattle',r:'Washington'},{n:'Denver',r:'Colorado'},{n:'Washington DC',r:'District of Columbia'},{n:'Nashville',r:'Tennessee'},{n:'Oklahoma City',r:'Oklahoma'},{n:'El Paso',r:'Texas'},{n:'Boston',r:'Massachusetts'},{n:'Portland',r:'Oregon'},{n:'Las Vegas',r:'Nevada'},{n:'Memphis',r:'Tennessee'},{n:'Louisville',r:'Kentucky'},{n:'Baltimore',r:'Maryland'},{n:'Milwaukee',r:'Wisconsin'},{n:'Albuquerque',r:'New Mexico'},{n:'Tucson',r:'Arizona'},{n:'Fresno',r:'California'},{n:'Sacramento',r:'California'},{n:'Kansas City',r:'Missouri'},{n:'Long Beach',r:'California'},{n:'Mesa',r:'Arizona'},{n:'Atlanta',r:'Georgia'},{n:'Colorado Springs',r:'Colorado'},{n:'Virginia Beach',r:'Virginia'},{n:'Raleigh',r:'North Carolina'},{n:'Omaha',r:'Nebraska'},{n:'Miami',r:'Florida'},{n:'Oakland',r:'California'},{n:'Minneapolis',r:'Minnesota'},{n:'Tulsa',r:'Oklahoma'},{n:'Wichita',r:'Kansas'},{n:'New Orleans',r:'Louisiana'},{n:'Arlington',r:'Texas'},{n:'Cleveland',r:'Ohio'},{n:'Honolulu',r:'Hawaii'},{n:'Orlando',r:'Florida'},{n:'Tampa',r:'Florida'},{n:'Pittsburgh',r:'Pennsylvania'},{n:'Cincinnati',r:'Ohio'},{n:'Detroit',r:'Michigan'},{n:'Minneapolis',r:'Minnesota'},{n:'Houston',r:'Texas'} ].map(c => ({ name: c.n, country: 'United States', region: c.r })),

  // Turkey (20+)
  ...[ {n:'Istanbul',r:'Istanbul'},{n:'Ankara',r:'Ankara'},{n:'İzmir',r:'İzmir'},{n:'Antalya',r:'Antalya'},{n:'Bursa',r:'Bursa'},{n:'Adana',r:'Adana'},{n:'Konya',r:'Konya'},{n:'Gaziantep',r:'Gaziantep'},{n:'Trabzon',r:'Trabzon'},{n:'Mersin',r:'Mersin'},{n:'Kayseri',r:'Kayseri'},{n:'Eskişehir',r:'Eskişehir'},{n:'Diyarbakır',r:'Diyarbakır'},{n:'Samsun',r:'Samsun'},{n:'Denizli',r:'Denizli'},{n:'Malatya',r:'Malatya'},{n:'Erzurum',r:'Erzurum'},{n:'Şanlıurfa',r:'Şanlıurfa'},{n:'Van',r:'Van'},{n:'Fethiye',r:'Muğla'} ].map(c => ({ name: c.n, country: 'Turkey', region: c.r })),

  // Thailand (20+)
  ...[ {n:'Bangkok',r:'Bangkok'},{n:'Chiang Mai',r:'Chiang Mai'},{n:'Phuket',r:'Phuket'},{n:'Pattaya',r:'Chonburi'},{n:'Krabi',r:'Krabi'},{n:'Koh Samui',r:'Surat Thani'},{n:'Chiang Rai',r:'Chiang Rai'},{n:'Udon Thani',r:'Udon Thani'},{n:'Khon Kaen',r:'Khon Kaen'},{n:'Nakhon Ratchasima',r:'Nakhon Ratchasima'},{n:'Hua Hin',r:'Prachuap Khiri Khan'},{n:'Kanchanaburi',r:'Kanchanaburi'},{n:'Ayutthaya',r:'Ayutthaya'},{n:'Songkhla',r:'Songkhla'},{n:'Ubon Ratchathani',r:'Ubon Ratchathani'},{n:'Hat Yai',r:'Songkhla'},{n:'Chanthaburi',r:'Chanthaburi'},{n:'Surat Thani',r:'Surat Thani'},{n:'Nonthaburi',r:'Nonthaburi'},{n:'Pak Kret',r:'Nonthaburi'} ].map(c => ({ name: c.n, country: 'Thailand', region: c.r })),

  // Iran (20+)
  ...[ {n:'Tehran',r:'Tehran'},{n:'Isfahan',r:'Isfahan'},{n:'Shiraz',r:'Fars'},{n:'Mashhad',r:'Khorasan-e Razavi'},{n:'Tabriz',r:'East Azerbaijan'},{n:'Karaj',r:'Alborz'},{n:'Ahvaz',r:'Khuzestan'},{n:'Qom',r:'Qom'},{n:'Kerman',r:'Kerman'},{n:'Urmia',r:'West Azerbaijan'},{n:'Rasht',r:'Gilan'},{n:'Sari',r:'Mazandaran'},{n:'Kermanshah',r:'Kermanshah'},{n:'Hamedan',r:'Hamedan'},{n:'Yazd',r:'Yazd'},{n:'Arak',r:'Markazi'},{n:'Bandar Abbas',r:'Hormozgan'},{n:'Zahedan',r:'Sistan and Baluchestan'},{n:'Sanandaj',r:'Kurdistan'},{n:'Gorgan',r:'Golestan'} ].map(c => ({ name: c.n, country: 'Iran', region: c.r })),

  // Spain (20+)
  ...[ {n:'Madrid',r:'Madrid'},{n:'Barcelona',r:'Cataluña'},{n:'Valencia',r:'Valencia'},{n:'Sevilla',r:'Andalucía'},{n:'Málaga',r:'Andalucía'},{n:'Bilbao',r:'País Vasco'},{n:'Alicante',r:'Valencia'},{n:'Zaragoza',r:'Aragón'},{n:'Granada',r:'Andalucía'},{n:'Palma',r:'Baleares'},{n:'Murcia',r:'Murcia'},{n:'Las Palmas',r:'Canarias'},{n:'Tenerife',r:'Canarias'},{n:'Córdoba',r:'Andalucía'},{n:'Valladolid',r:'Castilla y León'},{n:'Vigo',r:'Galicia'},{n:'Gijón',r:'Asturias'},{n:'Santander',r:'Cantabria'},{n:'Pamplona',r:'Navarra'},{n:'Salamanca',r:'Castilla y León'} ].map(c => ({ name: c.n, country: 'Spain', region: c.r })),

  // France (20+)
  ...[ {n:'Paris',r:'Île-de-France'},{n:'Marseille',r:'Provence-Alpes-Côte d\'Azur'},{n:'Lyon',r:'Auvergne-Rhône-Alpes'},{n:'Toulouse',r:'Occitanie'},{n:'Nice',r:'Provence-Alpes-Côte d\'Azur'},{n:'Nantes',r:'Pays de la Loire'},{n:'Strasbourg',r:'Grand Est'},{n:'Bordeaux',r:'Nouvelle-Aquitaine'},{n:'Montpellier',r:'Occitanie'},{n:'Rennes',r:'Bretagne'},{n:'Lille',r:'Hauts-de-France'},{n:'Reims',r:'Grand Est'},{n:'Toulon',r:'Provence-Alpes-Côte d\'Azur'},{n:'Le Havre',r:'Normandie'},{n:'Saint-Étienne',r:'Auvergne-Rhône-Alpes'},{n:'Grenoble',r:'Auvergne-Rhône-Alpes'},{n:'Dijon',r:'Bourgogne-Franche-Comté'},{n:'Angers',r:'Pays de la Loire'},{n:'Nîmes',r:'Occitanie'},{n:'Clermont-Ferrand',r:'Auvergne-Rhône-Alpes'} ].map(c => ({ name: c.n, country: 'France', region: c.r })),

  // Italy (20+)
  ...[ {n:'Rome',r:'Lazio'},{n:'Milan',r:'Lombardia'},{n:'Naples',r:'Campania'},{n:'Turin',r:'Piemonte'},{n:'Palermo',r:'Sicilia'},{n:'Genoa',r:'Liguria'},{n:'Bologna',r:'Emilia-Romagna'},{n:'Florence',r:'Toscana'},{n:'Bari',r:'Puglia'},{n:'Catania',r:'Sicilia'},{n:'Venice',r:'Veneto'},{n:'Verona',r:'Veneto'},{n:'Messina',r:'Sicilia'},{n:'Padua',r:'Veneto'},{n:'Trieste',r:'Friuli Venezia Giulia'},{n:'Brescia',r:'Lombardia'},{n:'Parma',r:'Emilia-Romagna'},{n:'Taranto',r:'Puglia'},{n:'Prato',r:'Toscana'},{n:'Modena',r:'Emilia-Romagna'} ].map(c => ({ name: c.n, country: 'Italy', region: c.r })),

  // UK (20+)
  ...[ {n:'London',r:'Greater London'},{n:'Manchester',r:'Greater Manchester'},{n:'Birmingham',r:'West Midlands'},{n:'Liverpool',r:'Merseyside'},{n:'Leeds',r:'West Yorkshire'},{n:'Glasgow',r:'Scotland'},{n:'Edinburgh',r:'Scotland'},{n:'Bristol',r:'Bristol'},{n:'Cardiff',r:'Wales'},{n:'Belfast',r:'Northern Ireland'},{n:'Sheffield',r:'South Yorkshire'},{n:'Newcastle',r:'Tyne and Wear'},{n:'Nottingham',r:'England'},{n:'Leicester',r:'England'},{n:'Coventry',r:'West Midlands'},{n:'Brighton',r:'England'},{n:'Oxford',r:'England'},{n:'Cambridge',r:'England'},{n:'York',r:'England'},{n:'Canterbury',r:'England'} ].map(c => ({ name: c.n, country: 'United Kingdom', region: c.r })),

  // Japan (20)
  ...[ {n:'Tokyo',r:'Tokyo'},{n:'Osaka',r:'Osaka'},{n:'Kyoto',r:'Kyoto'},{n:'Yokohama',r:'Kanagawa'},{n:'Nagoya',r:'Aichi'},{n:'Sapporo',r:'Hokkaido'},{n:'Fukuoka',r:'Fukuoka'},{n:'Kobe',r:'Hyogo'},{n:'Hiroshima',r:'Hiroshima'},{n:'Sendai',r:'Miyagi'},{n:'Naha',r:'Okinawa'},{n:'Chiba',r:'Chiba'},{n:'Saitama',r:'Saitama'},{n:'Niigata',r:'Niigata'},{n:'Nagano',r:'Nagano'},{n:'Shizuoka',r:'Shizuoka'},{n:'Kumamoto',r:'Kumamoto'},{n:'Kagoshima',r:'Kagoshima'},{n:'Mito',r:'Ibaraki'},{n:'Takamatsu',r:'Kagawa'} ].map(c => ({ name: c.n, country: 'Japan', region: c.r })),

  // China (20)
  ...[ {n:'Beijing',r:'Beijing'},{n:'Shanghai',r:'Shanghai'},{n:'Guangzhou',r:'Guangdong'},{n:'Shenzhen',r:'Guangdong'},{n:'Chengdu',r:'Sichuan'},{n:'Hangzhou',r:'Zhejiang'},{n:'Nanjing',r:'Jiangsu'},{n:'Wuhan',r:'Hubei'},{n:'Xi\'an',r:'Shaanxi'},{n:'Chongqing',r:'Chongqing'},{n:'Tianjin',r:'Tianjin'},{n:'Suzhou',r:'Jiangsu'},{n:'Qingdao',r:'Shandong'},{n:'Dalian',r:'Liaoning'},{n:'Xiamen',r:'Fujian'},{n:'Kunming',r:'Yunnan'},{n:'Harbin',r:'Heilongjiang'},{n:'Shenyang',r:'Liaoning'},{n:'Jinan',r:'Shandong'},{n:'Zhengzhou',r:'Henan'} ].map(c => ({ name: c.n, country: 'China', region: c.r })),

  // India (20)
  ...[ {n:'Mumbai',r:'Maharashtra'},{n:'Delhi',r:'Delhi'},{n:'Bangalore',r:'Karnataka'},{n:'Chennai',r:'Tamil Nadu'},{n:'Kolkata',r:'West Bengal'},{n:'Hyderabad',r:'Telangana'},{n:'Ahmedabad',r:'Gujarat'},{n:'Pune',r:'Maharashtra'},{n:'Jaipur',r:'Rajasthan'},{n:'Lucknow',r:'Uttar Pradesh'},{n:'Goa',r:'Goa'},{n:'Kochi',r:'Kerala'},{n:'Chandigarh',r:'Punjab'},{n:'Indore',r:'Madhya Pradesh'},{n:'Bhopal',r:'Madhya Pradesh'},{n:'Patna',r:'Bihar'},{n:'Visakhapatnam',r:'Andhra Pradesh'},{n:'Guwahati',r:'Assam'},{n:'Thiruvananthapuram',r:'Kerala'},{n:'Nagpur',r:'Maharashtra'} ].map(c => ({ name: c.n, country: 'India', region: c.r })),

  // Brazil (20)
  ...[ {n:'São Paulo',r:'São Paulo'},{n:'Rio de Janeiro',r:'Rio de Janeiro'},{n:'Brasília',r:'Goiás'},{n:'Salvador',r:'Bahia'},{n:'Fortaleza',r:'Ceará'},{n:'Belo Horizonte',r:'Minas Gerais'},{n:'Manaus',r:'Amazonas'},{n:'Curitiba',r:'Paraná'},{n:'Recife',r:'Pernambuco'},{n:'Porto Alegre',r:'Rio Grande do Sul'},{n:'Belém',r:'Pará'},{n:'Goiânia',r:'Goiás'},{n:'Guarulhos',r:'São Paulo'},{n:'Campinas',r:'São Paulo'},{n:'São Luís',r:'Maranhão'},{n:'Maceió',r:'Alagoas'},{n:'Natal',r:'Rio Grande do Norte'},{n:'Teresina',r:'Piauí'},{n:'Florianópolis',r:'Santa Catarina'},{n:'Vitória',r:'Espírito Santo'} ].map(c => ({ name: c.n, country: 'Brazil', region: c.r })),

  // Russia (20)
  ...[ {n:'Moscow',r:'Moscow'},{n:'Saint Petersburg',r:'Saint Petersburg'},{n:'Novosibirsk',r:'Novosibirsk'},{n:'Yekaterinburg',r:'Sverdlovsk'},{n:'Kazan',r:'Tatarstan'},{n:'Nizhny Novgorod',r:'Nizhny Novgorod'},{n:'Samara',r:'Samara'},{n:'Omsk',r:'Omsk'},{n:'Rostov-on-Don',r:'Rostov'},{n:'Chelyabinsk',r:'Chelyabinsk'},{n:'Krasnodar',r:'Krasnodar'},{n:'Voronezh',r:'Voronezh'},{n:'Perm',r:'Perm'},{n:'Volgograd',r:'Volgograd'},{n:'Krasnoyarsk',r:'Krasnoyarsk'},{n:'Saratov',r:'Saratov'},{n:'Tyumen',r:'Tyumen'},{n:'Tula',r:'Tula'},{n:'Kaliningrad',r:'Kaliningrad'},{n:'Murmansk',r:'Murmansk'} ].map(c => ({ name: c.n, country: 'Russia', region: c.r })),

  // Australia (15)
  ...[ {n:'Sydney',r:'New South Wales'},{n:'Melbourne',r:'Victoria'},{n:'Brisbane',r:'Queensland'},{n:'Perth',r:'Western Australia'},{n:'Adelaide',r:'South Australia'},{n:'Gold Coast',r:'Queensland'},{n:'Canberra',r:'Australian Capital Territory'},{n:'Hobart',r:'Tasmania'},{n:'Darwin',r:'Northern Territory'},{n:'Cairns',r:'Queensland'},{n:'Townsville',r:'Queensland'},{n:'Newcastle',r:'New South Wales'},{n:'Wollongong',r:'New South Wales'},{n:'Geelong',r:'Victoria'},{n:'Sunshine Coast',r:'Queensland'} ].map(c => ({ name: c.n, country: 'Australia', region: c.r })),

  // Canada (15)
  ...[ {n:'Toronto',r:'Ontario'},{n:'Montreal',r:'Quebec'},{n:'Vancouver',r:'British Columbia'},{n:'Calgary',r:'Alberta'},{n:'Edmonton',r:'Alberta'},{n:'Ottawa',r:'Ontario'},{n:'Winnipeg',r:'Manitoba'},{n:'Quebec City',r:'Quebec'},{n:'Hamilton',r:'Ontario'},{n:'Halifax',r:'Nova Scotia'},{n:'Victoria',r:'British Columbia'},{n:'Saskatoon',r:'Saskatchewan'},{n:'Regina',r:'Saskatchewan'},{n:'St. John\'s',r:'Newfoundland and Labrador'},{n:'Charlottetown',r:'Prince Edward Island'} ].map(c => ({ name: c.n, country: 'Canada', region: c.r })),

  // Mexico (15)
  ...[ {n:'Mexico City',r:'Ciudad de México'},{n:'Guadalajara',r:'Jalisco'},{n:'Monterrey',r:'Nuevo León'},{n:'Cancún',r:'Quintana Roo'},{n:'Mérida',r:'Yucatán'},{n:'Puebla',r:'Puebla'},{n:'Tijuana',r:'Baja California'},{n:'León',r:'Guanajuato'},{n:'Oaxaca',r:'Oaxaca'},{n:'Chihuahua',r:'Chihuahua'},{n:'Acapulco',r:'Guerrero'},{n:'Veracruz',r:'Veracruz'},{n:'Cabo San Lucas',r:'Baja California Sur'},{n:'Playa del Carmen',r:'Quintana Roo'},{n:'San Miguel de Allende',r:'Guanajuato'} ].map(c => ({ name: c.n, country: 'Mexico', region: c.r })),
]
